package com.example.thelaptopshope.Dta

import com.example.thelaptopshope.R

object FakeDTABASE {
    val owner = Owner("Sujal Khaire", "Developer & Love to pc build", R.drawable.kwner)
    val paymentD = listOf(Paymentdb(0,0,"Debit or Credit"),
                          Paymentdb(1,1,"Phone Pay"),
        Paymentdb(2,2,"Google Pay"),
        Paymentdb(3,3,"PayPal"),
        Paymentdb(4,4,"More Payment Setings"))
    val pcList = listOf(
       Pc(0,"Legion Pro 5 Gen 8 (16″ AMD) Gaming Laptop","340m away",R.drawable.lenovoleg, owner,"Given the Legion Slim 5 Gen 8's reasonable \$1,299 starting price, wealth of configuration options, and sturdy build, we can comfortably recommend this model to the average gamer. Our configuration (at \$1,549) is a little pricier than the base model, which gives you an idea of how it can scale up without coming close to high-end pricing. With an AMD Ryzen 7 7840HS CPU and Nvidia GeForce RTX 4060 GPU for speedy midrange gaming performance—alongside a sharp 165Hz display, a comfortable keyboard, and efficient cooling—this Legion is a worthy selection."),
       Pc(1,"MSI Titan 18 HX","578m away",R.drawable.msik, owner,"For the most power that money can buy today, your best bet is the MSI Titan 18 HX, which goes all-in for processing might. As the name suggests, this is a sizable 18-inch laptop, with virtually no concern for portability at 7.93 pounds. The latest Intel and Nvidia components are a chart-topping combination for gaming performance, with a supporting feature set that will make any shopper with a big budget happy. Its 4K mini LED panel with a 120Hz refresh rate is a major highlight, as well, but the performance is the obvious draw: The Intel Core i9-14900HX CPU and Nvidia GeForce RTX 4090 GPU in our review configuration made mincemeat of our benchmark tests, posting some unmatched raw 3D and gaming results."),
       Pc(2,"Alienware m18 R2","4545m",R.drawable.alen, owner,"The relatively new 18-inch laptop market is home to some of the most powerful gaming laptops available, allowing manufacturers to pack the best parts and robust thermal hardware into larger frames. This is the second edition of Dell's Alienware m18, carrying over a lot of what we liked from the first. Namely, this machine goes right to the top end of the power stack, complemented by high-end style and premium features like an advanced display. You can pick from a 1600p 165Hz or 1080p 480Hz panel, and our review unit was loaded with an Intel Core i9-14900HX CPU and an Nvidia GeForce RTX 4090 GPU. Unsurprisingly, this meant extreme performance as configured, and extra options like a Cherry MX mechanical keyboard elevated the experience even further."),
       Pc(3,"MSI Cyborg 15 (2023)","435m",R.drawable.cubo, owner,"If the Nitro isn't available or you find this laptop on sale, the Cyborg is a smart pick for budget-bound shoppers, young gamers getting their first gaming laptop, and anyone in those groups who especially wants a quick processor. The Nitro is something of a better deal, punching above its weight on performance, but you may prefer the Cyborg's build, or have your eye on the superior CPU and memory for other uses. Outside of that comparison, this remains one of the best ways to spend your money in this category"),
       Pc(4,"Asus ROG Zephyrus G14 (2024)","667m",R.drawable.rog, owner,"The G14 is our current favorite portable gaming laptop for its combination of performance, style, and price. Our \$1,999.99 review configuration is not cheap, but lightweight gaming laptops are inherently expensive, and this is a fine deal with an even more approachable \$1,599.99 base model. Our model packs an AMD Ryzen 9 8945HS processor, 32GB of RAM, a 1TB SSD, and an Nvidia GeForce RTX 4070 GPU into its compact frame. Frame rates easily cruised into the hundreds at 1080p and stayed well over 60fps even at native \"3K\" resolution. This performance comes in a stylish, high-quality chassis that weighs only 3.3 pounds, and it's realized through a 120Hz OLED panel with G-Sync support. Battery life is long, and you'll find plenty of ports despite its small frame. It's difficult to find much fault with the system, adding up to a capable, chic, and portable gaming machine."),
        Pc(0,"Legion Pro 5 Gen 8 (16″ AMD) Gaming Laptop","340m away",R.drawable.lenovoleg, owner,"Given the Legion Slim 5 Gen 8's reasonable \$1,299 starting price, wealth of configuration options, and sturdy build, we can comfortably recommend this model to the average gamer. Our configuration (at \$1,549) is a little pricier than the base model, which gives you an idea of how it can scale up without coming close to high-end pricing. With an AMD Ryzen 7 7840HS CPU and Nvidia GeForce RTX 4060 GPU for speedy midrange gaming performance—alongside a sharp 165Hz display, a comfortable keyboard, and efficient cooling—this Legion is a worthy selection."),
        Pc(1,"MSI Titan 18 HX","578m away",R.drawable.msik, owner,"For the most power that money can buy today, your best bet is the MSI Titan 18 HX, which goes all-in for processing might. As the name suggests, this is a sizable 18-inch laptop, with virtually no concern for portability at 7.93 pounds. The latest Intel and Nvidia components are a chart-topping combination for gaming performance, with a supporting feature set that will make any shopper with a big budget happy. Its 4K mini LED panel with a 120Hz refresh rate is a major highlight, as well, but the performance is the obvious draw: The Intel Core i9-14900HX CPU and Nvidia GeForce RTX 4090 GPU in our review configuration made mincemeat of our benchmark tests, posting some unmatched raw 3D and gaming results."),
        Pc(2,"Alienware m18 R2","4545m",R.drawable.alen, owner,"The relatively new 18-inch laptop market is home to some of the most powerful gaming laptops available, allowing manufacturers to pack the best parts and robust thermal hardware into larger frames. This is the second edition of Dell's Alienware m18, carrying over a lot of what we liked from the first. Namely, this machine goes right to the top end of the power stack, complemented by high-end style and premium features like an advanced display. You can pick from a 1600p 165Hz or 1080p 480Hz panel, and our review unit was loaded with an Intel Core i9-14900HX CPU and an Nvidia GeForce RTX 4090 GPU. Unsurprisingly, this meant extreme performance as configured, and extra options like a Cherry MX mechanical keyboard elevated the experience even further."),
        Pc(3,"MSI Cyborg 15 (2023)","435m",R.drawable.cubo, owner,"If the Nitro isn't available or you find this laptop on sale, the Cyborg is a smart pick for budget-bound shoppers, young gamers getting their first gaming laptop, and anyone in those groups who especially wants a quick processor. The Nitro is something of a better deal, punching above its weight on performance, but you may prefer the Cyborg's build, or have your eye on the superior CPU and memory for other uses. Outside of that comparison, this remains one of the best ways to spend your money in this category"),
        Pc(4,"Asus ROG Zephyrus G14 (2024)","667m",R.drawable.rog, owner,"The G14 is our current favorite portable gaming laptop for its combination of performance, style, and price. Our \$1,999.99 review configuration is not cheap, but lightweight gaming laptops are inherently expensive, and this is a fine deal with an even more approachable \$1,599.99 base model. Our model packs an AMD Ryzen 9 8945HS processor, 32GB of RAM, a 1TB SSD, and an Nvidia GeForce RTX 4070 GPU into its compact frame. Frame rates easily cruised into the hundreds at 1080p and stayed well over 60fps even at native \"3K\" resolution. This performance comes in a stylish, high-quality chassis that weighs only 3.3 pounds, and it's realized through a 120Hz OLED panel with G-Sync support. Battery life is long, and you'll find plenty of ports despite its small frame. It's difficult to find much fault with the system, adding up to a capable, chic, and portable gaming machine."),
       Pc(1,"MSI Titan 18 HX","578m away",R.drawable.msik, owner,"For the most power that money can buy today, your best bet is the MSI Titan 18 HX, which goes all-in for processing might. As the name suggests, this is a sizable 18-inch laptop, with virtually no concern for portability at 7.93 pounds. The latest Intel and Nvidia components are a chart-topping combination for gaming performance, with a supporting feature set that will make any shopper with a big budget happy. Its 4K mini LED panel with a 120Hz refresh rate is a major highlight, as well, but the performance is the obvious draw: The Intel Core i9-14900HX CPU and Nvidia GeForce RTX 4090 GPU in our review configuration made mincemeat of our benchmark tests, posting some unmatched raw 3D and gaming results."),
       Pc(2,"Alienware m18 R2","4545m",R.drawable.alen, owner,"The relatively new 18-inch laptop market is home to some of the most powerful gaming laptops available, allowing manufacturers to pack the best parts and robust thermal hardware into larger frames. This is the second edition of Dell's Alienware m18, carrying over a lot of what we liked from the first. Namely, this machine goes right to the top end of the power stack, complemented by high-end style and premium features like an advanced display. You can pick from a 1600p 165Hz or 1080p 480Hz panel, and our review unit was loaded with an Intel Core i9-14900HX CPU and an Nvidia GeForce RTX 4090 GPU. Unsurprisingly, this meant extreme performance as configured, and extra options like a Cherry MX mechanical keyboard elevated the experience even further."),
       Pc(3,"MSI Cyborg 15 (2023)","435m",R.drawable.cubo, owner,"If the Nitro isn't available or you find this laptop on sale, the Cyborg is a smart pick for budget-bound shoppers, young gamers getting their first gaming laptop, and anyone in those groups who especially wants a quick processor. The Nitro is something of a better deal, punching above its weight on performance, but you may prefer the Cyborg's build, or have your eye on the superior CPU and memory for other uses. Outside of that comparison, this remains one of the best ways to spend your money in this category"),
       Pc(4,"Asus ROG Zephyrus G14 (2024)","667m",R.drawable.rog, owner,"The G14 is our current favorite portable gaming laptop for its combination of performance, style, and price. Our \$1,999.99 review configuration is not cheap, but lightweight gaming laptops are inherently expensive, and this is a fine deal with an even more approachable \$1,599.99 base model. Our model packs an AMD Ryzen 9 8945HS processor, 32GB of RAM, a 1TB SSD, and an Nvidia GeForce RTX 4070 GPU into its compact frame. Frame rates easily cruised into the hundreds at 1080p and stayed well over 60fps even at native \"3K\" resolution. This performance comes in a stylish, high-quality chassis that weighs only 3.3 pounds, and it's realized through a 120Hz OLED panel with G-Sync support. Battery life is long, and you'll find plenty of ports despite its small frame. It's difficult to find much fault with the system, adding up to a capable, chic, and portable gaming machine."),
        Pc(0,"Legion Pro 5 Gen 8 (16″ AMD) Gaming Laptop","340m away",R.drawable.lenovoleg, owner,"Given the Legion Slim 5 Gen 8's reasonable \$1,299 starting price, wealth of configuration options, and sturdy build, we can comfortably recommend this model to the average gamer. Our configuration (at \$1,549) is a little pricier than the base model, which gives you an idea of how it can scale up without coming close to high-end pricing. With an AMD Ryzen 7 7840HS CPU and Nvidia GeForce RTX 4060 GPU for speedy midrange gaming performance—alongside a sharp 165Hz display, a comfortable keyboard, and efficient cooling—this Legion is a worthy selection."),
        Pc(1,"MSI Titan 18 HX","578m away",R.drawable.msik, owner,"For the most power that money can buy today, your best bet is the MSI Titan 18 HX, which goes all-in for processing might. As the name suggests, this is a sizable 18-inch laptop, with virtually no concern for portability at 7.93 pounds. The latest Intel and Nvidia components are a chart-topping combination for gaming performance, with a supporting feature set that will make any shopper with a big budget happy. Its 4K mini LED panel with a 120Hz refresh rate is a major highlight, as well, but the performance is the obvious draw: The Intel Core i9-14900HX CPU and Nvidia GeForce RTX 4090 GPU in our review configuration made mincemeat of our benchmark tests, posting some unmatched raw 3D and gaming results."),
        Pc(2,"Alienware m18 R2","4545m",R.drawable.alen, owner,"The relatively new 18-inch laptop market is home to some of the most powerful gaming laptops available, allowing manufacturers to pack the best parts and robust thermal hardware into larger frames. This is the second edition of Dell's Alienware m18, carrying over a lot of what we liked from the first. Namely, this machine goes right to the top end of the power stack, complemented by high-end style and premium features like an advanced display. You can pick from a 1600p 165Hz or 1080p 480Hz panel, and our review unit was loaded with an Intel Core i9-14900HX CPU and an Nvidia GeForce RTX 4090 GPU. Unsurprisingly, this meant extreme performance as configured, and extra options like a Cherry MX mechanical keyboard elevated the experience even further."),
        Pc(3,"MSI Cyborg 15 (2023)","435m",R.drawable.cubo, owner,"If the Nitro isn't available or you find this laptop on sale, the Cyborg is a smart pick for budget-bound shoppers, young gamers getting their first gaming laptop, and anyone in those groups who especially wants a quick processor. The Nitro is something of a better deal, punching above its weight on performance, but you may prefer the Cyborg's build, or have your eye on the superior CPU and memory for other uses. Outside of that comparison, this remains one of the best ways to spend your money in this category"),
        Pc(4,"Asus ROG Zephyrus G14 (2024)","667m",R.drawable.rog, owner,"The G14 is our current favorite portable gaming laptop for its combination of performance, style, and price. Our \$1,999.99 review configuration is not cheap, but lightweight gaming laptops are inherently expensive, and this is a fine deal with an even more approachable \$1,599.99 base model. Our model packs an AMD Ryzen 9 8945HS processor, 32GB of RAM, a 1TB SSD, and an Nvidia GeForce RTX 4070 GPU into its compact frame. Frame rates easily cruised into the hundreds at 1080p and stayed well over 60fps even at native \"3K\" resolution. This performance comes in a stylish, high-quality chassis that weighs only 3.3 pounds, and it's realized through a 120Hz OLED panel with G-Sync support. Battery life is long, and you'll find plenty of ports despite its small frame. It's difficult to find much fault with the system, adding up to a capable, chic, and portable gaming machine."))}






